### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by ojz0r** [arranlomas/Trickl#22]
Could you please post a permission list with an explaination why thsy are needed?

I see some permissions and i dont know why they are needed.

Thank you.

**Comment by anacrolix** [comment]
I'm only seeing storage on my Android. That's for the data cache and downloads. If you have network that would be pretty obvious. What else are you seeing?

**Comment by ojz0r** [comment]
Yes in the built in permission manager.

However i'm using the xposed module "xprivacy" that lists all permission for apps with toggles for on and off.
The permissions i block that crashes the app is:
- email/GMailProvider
- identification/%cid
- phone/Configuration.MNC
- phone/Configuration.MCC
- identification/SERIAL

I cant imagine why those would be needed for a torrent client. Maybe there is a good explaination, or just junk from the compiler.

**Comment by arranlomas** [comment]
Hi sorry I am a little confused about what these permissions actually are?

You can see all the permissions I use in the manifest https://github.com/arranlomas/Trickl/blob/master/app/src/main/AndroidManifest.xml

I think its pretty self explanatory why I need the permissions in there,

storage for read write to download
Internet (which is granted by default) to access the internet
Access network state to enable wifi only for downloads and cancel downloads if network state changed.

I need to look more into the xprivacy app to find out why those permissions are showing up but are these also present in other apps? What about in other torrent apps? LibreTorrent etc, do they show up there?

Also I am not sure how I could stop it crashing? I don't use a rooted advice so I won't be able to replicate this, if you can find a satisfactory way to stop it crashing I am open to pull requests.


For now I am going to close the issue because all the permissions I request are necessary and I am not sure what the permissions you mention actually are and a quick google didn't turn much up. If others feel this is a major issue I will re-open.

Thanks for commenting, and I will keep an eye on this issue!
