### ISSUE TITLE
cant able to compile

### ISSUE THREAD

**Issue by hirenkharsani** [arranlomas/Trickl#23]
hi
I am very new to kotlin can you please help I am getting error while compiling here

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

its says that Error:(10, 0) I:\Trickl-master_2\Trickl-master\keystore.properties (The system cannot find the file specified)

can you please help on this. thanks in advance.

**Comment by arranlomas** [comment]
Hello, so this is an issue with fabric. I use Fabric to monitor crashes and help resolve issues. 

There are a few ways to resolve this. You can remove the fabric dependency or you can add a project in fabric and create a keystore.properties and add your fabric api key there, for obvious reasons I gitignore this file in the public repo. 

Feel free to open this issue again if you have some trouble

**Comment by arranlomas** [comment]
I have added a new section in the readme. If you have any other issues that you solve please feel free to make a pull request detailing the problems you solved. Thanks

**Comment by hirenkharsani** [comment]
hi, thanks for your reply.
first of all, I forgot to mention that this application is by far the great I have ever used.
I recently bought the cromecast and experience cromecast with this is awesome.
I tried to remove fabric dependency and then it gives another error when I'm going to run it on the device.
Here is the screenshot.
![error](https://user-images.githubusercontent.com/23076498/33512287-3cecb8dc-d753-11e7-924e-0cb6d2bf1cf3.png)

**Comment by arranlomas** [comment]
Hi. Thanks for the compliments glad you like the app! 

This block returns the string for the api that provides the search results. Here you can just return an empty string. However, If you do want to get search results then follow the steps in this repo: https://github.com/arranlomas/TPBScraper to compile and deploy the webapp and then put the URL where you deployed it in the return string here. 

I am going to reopen this issue as I can forsee some other issues coming up.

I haven't gone through the build process from the GitHub repo as there are some  other things that may create issues. I will clone the repo again and go through the setup and update the readme to hopefully cover all of your issues instead of you having to comment here each time. 

Thanks again!

**Comment by arranlomas** [comment]
@hirenkharsani I have updated so hopefully the instructions are a bit clearer, if your still unsure let me know here
